export const GET_CHARACTERS = 'GET_CHARACTERS'
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE'
export const DELETE_FROM_FAVORITE = 'DELETE_FROM_FAVORITE'
export const EDIT_FAVORITE = 'EDIT_FAVORITE'
